### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by karthiak23** [open-data-plan/g2plot-react#103]
**Describe the bug**
    Type 'GuideLineConfig | undefined' is not assignable to type 'GuideLineConfig[] | undefined'.
I am getting this error.

**To Reproduce**
Just followed the implementation steps

**Expected behavior**
Render the antv g2plot charts

**Desktop (please complete the following information):**
 - Browser [e.g. chrome]

**Comment by kagawagao** [comment]
can you provide a mini showcase or error context?

I've tried to reproduce, but nothing happened

> FYI: there is a known bug in `g2plot`, `guideLine` not work in current version
