### ISSUE TITLE
[Bug] Error on Install

### ISSUE THREAD

**Issue by matheus-garcia** [open-data-plan/g2plot-react#135]
**Describe the bug**
After installing g2plot I see many bugs on my console, even after restarting my React app, the issues still persist

**To Reproduce**
1. Install
2. Run React App
3. Check console Logs 

**Expected behavior**
Use g2plot components

**Screenshots**
![error](https://user-images.githubusercontent.com/21963240/86026834-52cda380-ba06-11ea-9710-76c27d551727.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera/Chrome

**Comment by kagawagao** [comment]
@matheus-garcia is @antv/g2plot installed?

**Comment by matheus-garcia** [comment]
I've used npm install @opd/g2plot-react, but it seems it didn't install, even without console errors, do you know how can I handle that?

**Comment by matheus-garcia** [comment]
Actually not a bug... as you said I was missing @antv/g2plot dependecy.

Could you please update the DOCs to make sure it is necessary to install @antv/g2plot to use @antv/g2plot-react.

Thanks for your help.

**Comment by kagawagao** [comment]
after `@opd/g2plot-react` `v1.5.0`, `@antv/g2plot` has been moved to peer dependencies, if you run `npm install @opd/g2plot-react`, npm will log this message in your console
