### ISSUE TITLE
可以添加到 G2Plot wiki 中

### ISSUE THREAD

**Issue by hustcc** [open-data-plan/g2plot-react#178]
具体地址：https://github.com/antvis/G2Plot/wiki/Developer

**Comment by kagawagao** [comment]
| 项目名                                                                | 技术栈    | 描述                                                     | 版本                                                                                                          |
| --------------------------------------------------------------------- | --------- | -------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------- |
| [@ant-design/charts](https://github.com/ant-design/ant-design-charts) | **React** | A React Chart Library based on `@antvis/G2Plot`.         | ![npm](https://img.shields.io/npm/v/@ant-design/charts)                                                       |
| [React-G2Plot](https://github.com/hustcc/React-G2Plot)                | **React** | Unofficial react component wrapper for `@antvis/G2Plot`. | [![npm](https://img.shields.io/npm/v/react-g2plot.svg)](https://www.npmjs.com/package/react-g2plot)           |
| [G2Plot-React](https://github.com/open-data-plan/g2plot-react)        | **React** | G2Plot for React.                                        | [![npm](https://img.shields.io/npm/v/@opd/g2plot-react.svg)](https://www.npmjs.com/package/@opd/g2plot-react) |
| [G2Plot-Vue](https://github.com/open-data-plan/g2plot-vue)            | **Vue 3** | G2Plot for Vue 3.                                        | [![npm](https://img.shields.io/npm/v/@opd/g2plot-vue.svg)](https://www.npmjs.com/package/@opd/g2plot-vue)     |


@hustcc

**Comment by hustcc** [comment]
你不能直接编辑是吧？
另外看你在找工作，简历给我一份？我微信看我主页介绍。

**Comment by kagawagao** [comment]
没权限编辑

工作目前只能看重庆的

**Comment by hustcc** [comment]
看来要放到一个可以 pr 的地方。
重庆确实没有岗位^_^

**Comment by hustcc** [comment]
已经直接加到网站的中了，wiki 不能协同，还是废弃了。

https://github.com/antvis/G2Plot/pull/1637/files#diff-30f35ef4fc8d62db1f7a7740997ff8aaR6
