### ISSUE TITLE
[Bug] Chart Background shows [object Object]

### ISSUE THREAD

**Issue by TharinduDG** [open-data-plan/g2plot-react#572]
**Describe the bug**
`LineChart` background showing `[object Object]`

**Screenshots**
<img width="423" alt="Screenshot 2022-09-11 at 18 43 58" src="https://user-images.githubusercontent.com/1578747/189539312-f91c556d-5c98-41f5-8a57-25605dee4b72.png">

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS 12.2
- Browser [e.g. chrome, safari]: Chrome
- `@antv/g2plot` Version [e.g. v2.3.12] 
- `@opd/g2plot-react` Version [e.g. v2.7.0] v2.12.0

**Additional context**

**Comment by kagawagao** [comment]
@TharinduDG please provide a mini showcase or base options
